-- D2: 비밀번호 재설정 단명 토큰 (해시 저장)
CREATE TABLE password_reset_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT      NOT NULL REFERENCES account (id),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX password_reset_account_idx ON password_reset_token (account_id);
