-- 계정 (3-tier 통합). client_org FK는 B1(client_org 생성)에서 추가.
CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    name          VARCHAR(50)  NOT NULL,
    tier          VARCHAR(20)  NOT NULL CHECK (tier IN ('admin','team','client')),
    job           VARCHAR(20)            CHECK (job IN ('pm','planner','designer','developer','qa')),
    client_org_id BIGINT,
    password_hash VARCHAR(255),
    status        VARCHAR(20)  NOT NULL DEFAULT 'pending' CHECK (status IN ('active','pending','inactive')),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX account_email_uq ON account (lower(email));
