-- B1: 조직·프로젝트·멤버십·초대·게이트

CREATE TABLE client_org (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- account: V2에서 미룬 FK + tier별 일관성 CHECK 부여
ALTER TABLE account
    ADD CONSTRAINT fk_account_client_org FOREIGN KEY (client_org_id) REFERENCES client_org (id),
    ADD CONSTRAINT ck_account_tier_consistency CHECK (
        (tier = 'client' AND client_org_id IS NOT NULL AND job IS NULL)
        OR (tier = 'team' AND job IS NOT NULL AND client_org_id IS NULL)
        OR (tier = 'admin' AND job IS NULL AND client_org_id IS NULL)
    );

CREATE TABLE project (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    client_org_id BIGINT       NOT NULL REFERENCES client_org (id),
    type          VARCHAR(20)  CHECK (type IN ('SaaS', '웹사이트', '모바일')),
    description   TEXT,
    start_date    DATE,
    end_date      DATE,
    current_stage SMALLINT     NOT NULL DEFAULT 1,
    status        VARCHAR(20)  NOT NULL DEFAULT 'active',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_project_dates CHECK (start_date IS NULL OR end_date IS NULL OR end_date >= start_date)
);
CREATE INDEX project_client_org_idx ON project (client_org_id);

CREATE TABLE project_member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT      NOT NULL REFERENCES project (id),
    account_id BIGINT      NOT NULL REFERENCES account (id),
    invited_by BIGINT      REFERENCES account (id),
    joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at    TIMESTAMPTZ,
    CONSTRAINT uq_project_member UNIQUE (project_id, account_id)
);
-- 내 활성 참여 조회용
CREATE INDEX project_member_account_active_idx ON project_member (account_id) WHERE left_at IS NULL;

CREATE TABLE invitation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    project_id  BIGINT       NOT NULL REFERENCES project (id),
    invite_type VARCHAR(20)  NOT NULL CHECK (invite_type IN ('client', 'team_member')),
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    status      VARCHAR(20)  NOT NULL CHECK (status IN ('pending', 'accepted', 'expired')),
    invited_by  BIGINT       NOT NULL REFERENCES account (id),
    expires_at  TIMESTAMPTZ  NOT NULL,
    accepted_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- 활성(pending) 중복 초대 방지
CREATE UNIQUE INDEX invitation_active_uq
    ON invitation (project_id, lower(email), invite_type) WHERE status = 'pending';

CREATE TABLE project_gate (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT      NOT NULL REFERENCES project (id),
    gate_stage SMALLINT    NOT NULL CHECK (gate_stage IN (9, 11, 13, 15, 22)),
    status     VARCHAR(10) NOT NULL CHECK (status IN ('pass', 'wait', 'lock')),
    passed_at  TIMESTAMPTZ,
    passed_by  BIGINT      REFERENCES account (id),
    CONSTRAINT uq_project_gate UNIQUE (project_id, gate_stage)
);
