-- B2: 산출물 슬롯·버전·파일

CREATE TABLE deliverable_slot (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id         BIGINT      NOT NULL REFERENCES project (id),
    slot_type          VARCHAR(20) NOT NULL CHECK (slot_type IN ('requirements', 'ia', 'design', 'prototype', 'figma')),
    current_version_id BIGINT,
    status             VARCHAR(20) NOT NULL DEFAULT 'empty'
                           CHECK (status IN ('empty', 'draft', 'pending-review', 'confirmed', 'rejected')),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_slot_project_type UNIQUE (project_id, slot_type)
);

CREATE TABLE slot_version (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id                       BIGINT      NOT NULL REFERENCES deliverable_slot (id),
    version_no                    SMALLINT    NOT NULL,
    status                        VARCHAR(20) NOT NULL
                                      CHECK (status IN ('draft', 'pending-review', 'confirmed', 'rejected')),
    change_summary                TEXT,
    created_by                    BIGINT      NOT NULL REFERENCES account (id),
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    review_requested_by           BIGINT      REFERENCES account (id),
    review_requested_at           TIMESTAMPTZ,
    reviewed_by                   BIGINT      REFERENCES account (id),
    reviewed_at                   TIMESTAMPTZ,
    confirmed_upstream_version_id BIGINT      REFERENCES slot_version (id),
    CONSTRAINT uq_version_slot_no UNIQUE (slot_id, version_no),
    CONSTRAINT uq_version_slot_id UNIQUE (slot_id, id),
    CONSTRAINT ck_version_review_consistency CHECK (
        (status = 'draft'
            AND review_requested_by IS NULL AND review_requested_at IS NULL
            AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR (status = 'pending-review'
            AND review_requested_by IS NOT NULL AND review_requested_at IS NOT NULL
            AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR (status IN ('confirmed', 'rejected')
            AND review_requested_by IS NOT NULL AND review_requested_at IS NOT NULL
            AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);
-- 슬롯당 검토중 버전 1개
CREATE UNIQUE INDEX slot_version_pending_uq ON slot_version (slot_id) WHERE status = 'pending-review';

-- 최신 버전 캐시 포인터: 타 슬롯 버전 참조 방지(복합 FK)
ALTER TABLE deliverable_slot
    ADD CONSTRAINT fk_slot_current_version
        FOREIGN KEY (id, current_version_id) REFERENCES slot_version (slot_id, id);

CREATE TABLE file_asset (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_version_id BIGINT       NOT NULL REFERENCES slot_version (id),
    asset_kind      VARCHAR(10)  NOT NULL DEFAULT 'file' CHECK (asset_kind IN ('file', 'url')),
    logical_key     VARCHAR(255) NOT NULL,
    position        INT          NOT NULL DEFAULT 0,
    original_name   VARCHAR(255) NOT NULL,
    description     VARCHAR(255),
    content_type    VARCHAR(100),
    size_bytes      BIGINT       CHECK (size_bytes IS NULL OR size_bytes <= 50 * 1024 * 1024),
    storage_key     VARCHAR(512),
    external_url    VARCHAR(2048),
    uploaded_by     BIGINT       NOT NULL REFERENCES account (id),
    uploaded_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_asset_kind_fields CHECK (
        (asset_kind = 'file' AND storage_key IS NOT NULL AND content_type IS NOT NULL AND size_bytes IS NOT NULL)
        OR (asset_kind = 'url' AND external_url IS NOT NULL)
    ),
    CONSTRAINT uq_asset_version_key UNIQUE (slot_version_id, logical_key)
);
-- file 한정 storage_key 유일
CREATE UNIQUE INDEX file_asset_storage_key_uq ON file_asset (storage_key) WHERE asset_kind = 'file';
CREATE INDEX file_asset_version_idx ON file_asset (slot_version_id, position);
