-- B3: 활동 이력 (시스템 이벤트, append-only)
CREATE TABLE activity_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id         BIGINT      NOT NULL REFERENCES deliverable_slot (id),
    event_type      VARCHAR(30) NOT NULL CHECK (event_type IN (
                        'version_created', 'review_requested', 'review_recalled',
                        'confirmed', 'rejected', 'invalidated', 'upstream_reviewed')),
    slot_version_id BIGINT      REFERENCES slot_version (id),
    actor_id        BIGINT      NOT NULL REFERENCES account (id),
    body            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX activity_event_slot_idx ON activity_event (slot_id, created_at);
