-- B5: 코멘트 (슬롯 버전 또는 결함에 귀속, 정확히 하나)
-- defect_id FK는 Phase C(defect 테이블 생성)에서 추가.
CREATE TABLE comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_version_id BIGINT      REFERENCES slot_version (id),
    defect_id       BIGINT,
    author_id       BIGINT      NOT NULL REFERENCES account (id),
    body            TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    edited_at       TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT ck_comment_owner CHECK ((slot_version_id IS NOT NULL) <> (defect_id IS NOT NULL))
);
CREATE INDEX comment_version_idx ON comment (slot_version_id, created_at) WHERE deleted_at IS NULL;
