-- C: 개발(코드 자동 생성) 트리거 실행 이력 (REQ-DEV-001)
CREATE TABLE dev_run (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT      NOT NULL REFERENCES project (id),
    result       VARCHAR(10) NOT NULL CHECK (result IN ('success', 'fail')),
    reason       TEXT,
    triggered_by BIGINT      REFERENCES account (id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX dev_run_project_idx ON dev_run (project_id, created_at DESC);
