-- C②: 테스트 케이스·결함 (UAT 루프)

-- 프로젝트별 업무코드 채번 (TC-NNN / DEF-NNN)
CREATE TABLE code_sequence (
    project_id  BIGINT      NOT NULL REFERENCES project (id),
    entity_type VARCHAR(20) NOT NULL CHECK (entity_type IN ('test_case', 'defect')),
    next_no     INT         NOT NULL DEFAULT 1,
    PRIMARY KEY (project_id, entity_type)
);

CREATE TABLE test_case (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT      NOT NULL REFERENCES project (id),
    code            VARCHAR(20) NOT NULL,
    title           VARCHAR(200) NOT NULL,
    phase           VARCHAR(30) NOT NULL,
    priority        VARCHAR(10) NOT NULL CHECK (priority IN ('High', 'Medium', 'Low')),
    status          VARCHAR(10) NOT NULL DEFAULT 'pending' CHECK (status IN ('passed', 'failed', 'pending')),
    precondition    TEXT,
    steps           TEXT,
    expected_result TEXT,
    actual_result   TEXT,
    assignee_id     BIGINT      REFERENCES account (id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tc_project_code UNIQUE (project_id, code)
);
CREATE INDEX test_case_project_idx ON test_case (project_id, code);

CREATE TABLE defect (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT      NOT NULL REFERENCES project (id),
    code        VARCHAR(20) NOT NULL,
    title       VARCHAR(200) NOT NULL,
    severity    VARCHAR(10) NOT NULL CHECK (severity IN ('High', 'Medium', 'Low')),
    status      VARCHAR(15) NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'in_progress', 'resolved', 'cannot_reproduce')),
    repro_steps TEXT,
    environment VARCHAR(200),
    reporter_id BIGINT      REFERENCES account (id),
    assignee_id BIGINT      REFERENCES account (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_def_project_code UNIQUE (project_id, code)
);
CREATE INDEX defect_project_idx ON defect (project_id, code);

-- V6에서 미룬 comment.defect_id FK (이제 defect 존재)
ALTER TABLE comment ADD CONSTRAINT fk_comment_defect FOREIGN KEY (defect_id) REFERENCES defect (id);

CREATE TABLE test_defect_link (
    test_case_id BIGINT      NOT NULL REFERENCES test_case (id),
    defect_id    BIGINT      NOT NULL REFERENCES defect (id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (test_case_id, defect_id)
);

CREATE TABLE defect_attachment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    defect_id     BIGINT      NOT NULL REFERENCES defect (id),
    original_name VARCHAR(255) NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    BIGINT      NOT NULL CHECK (size_bytes <= 50 * 1024 * 1024),
    storage_key   VARCHAR(512) NOT NULL,
    uploaded_by   BIGINT      NOT NULL REFERENCES account (id),
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX defect_attachment_idx ON defect_attachment (defect_id);
