-- C③: 알림 + 감사 로그
CREATE TABLE notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT      NOT NULL REFERENCES account (id),
    type         VARCHAR(30) NOT NULL,
    body         TEXT        NOT NULL,
    link         VARCHAR(512),
    is_read      BOOLEAN     NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX notification_recipient_idx ON notification (recipient_id, is_read, created_at DESC);

-- 감사 로그 (append-only, REQ-AUD-001)
CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id   BIGINT      REFERENCES account (id) ON DELETE SET NULL,
    actor_role VARCHAR(20) NOT NULL,
    action     VARCHAR(100) NOT NULL,
    target     VARCHAR(255),
    ip         INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_created_idx ON audit_log (created_at DESC);
